### PR TITLE
Sean

### PR DESCRIPTION
**Pull request by slucey**
Here are the updated functions with roxygen parameters updated as well.  Will still need to run through the examples and probably update the vignettes.

### CODE REVIEW

**Comment by andybeet** [comment]
The function `all_of` isn't found. If it is part of a package which `survdat` already depends on then let's reference it by the package name. If we need to add another package dependency, lets do that, but if this is the only function used from a new dependent package, then i think we can rewrite this line.

**Comment by slucey** [comment]
@andybeet I can't find the `all_of` function in the code and don't even remember using it.  Which function is it in?  Also, `areaDescription` should always be a single column.  Is there somewhere where it is referencing more than one column?

**Comment by slucey** [comment]
Removed `all_of` ... seems to still work.

**Comment by andybeet** [comment]
@slucey looks good.

**Pull request merged**
